---

### SQL option group parameters###

option_group_name: "sqlserver-se-option-group"
engine_name : "sqlserver-se"
major_engine_version: "15.00"
option_group_description: "test mssql option group"
option_name: "SSRS"
option_group_port: 8443
vpc_security_group_memberships: "sg-0b27a3e4ba4eae927"

### RDS variables ###

allocated_storage: 20
instance_class: "db.t3.xlarge" 
instance_identifier: "my-db-instance"
subnet_group_name: "default" 
db_engine: "sqlserver-se"
db_engine_version: "15.00.4236.7.v1"
master_passwd: "rootroot"
master_username: "root"
max_allocated_storage: 100
port: "1433"
region: "ap-south-1"
storage_type: "gp2"
vpc_security_group_id: "sg-0b27a3e4ba4eae927"
