---
#- name: Create an RDS sql option group
 # community.aws.rds_option_group:
  #  state: present
  #  option_group_name: "{{ option_group_name }}"
  #  engine_name: "{{ engine_name }}"
  #  major_engine_version: "{{ major_engine_version }}"
  #  option_group_description: "{{  option_group_description }}"
  #  region: "{{ region }}"
  #  apply_immediately: true
  #  options:
   #     - option_name: "{{ option_name }}"
   #       port: "{{ option_group_port }}"
   #       vpc_security_group_memberships:
   #          - "{{ vpc_security_group_memberships }}"
#  register: new_rds_mssql_option_group

- name: create RDS instance
  community.aws.rds_instance:
    region: "{{ region }}"
    state: "present"
    engine: "{{ db_engine }}"
    license_model: "license-included"
    engine_version: "{{ db_engine_version }}"
    db_instance_identifier: "{{ instance_identifier}}"
    master_username: "{{ master_username }}"
    master_user_password: "{{ master_passwd }}"
    db_instance_class: "{{ instance_class }}"
    storage_type: "{{ storage_type }}"
    allocated_storage: "{{ allocated_storage }}"
    max_allocated_storage: "{{ max_allocated_storage }}"
    multi_az: "{{ multi_az }}"
    db_subnet_group_name: "{{ subnet_group_name }}"
    publicly_accessible: "{{ publicly_accessible }}"
    vpc_security_group_ids: "{{ vpc_security_group_id }}"
    port: "{{ port }}"
    backup_retention_period: 7
    storage_encrypted: "{{ storage_encrypted }}"
    kms_key_id: "{{ kms_key_id  }}"
    db_parameter_group_name: "{{ db_parameter_group_name }}"
    option_group_name: "{{ option_group_name }}"
    timezone: "{{ timezone }}"
    auto_minor_version_upgrade: "{{ auto_minor_version_upgrade }}"
    apply_immediately: "{{ apply_immediately }}"
    wait: "{{ wait }}"
    enable_iam_database_authentication: "{{ enable_iam_database_authentication }}"
    debug_botocore_endpoint_logs: "{{ debug_botocore_endpoint_logs }}"
    deletion_protection: "{{ deletion_protection }}"
    apply_immediately: "{{ apply_immediately }}"
    force_failover: "{{ force_failover }}"
    read_replica: "{{ read_replica }}"
    copy_tags_to_snapshot: "{{ copy_tags_to_snapshot }}"
    allow_major_version_upgrade: "{{ allow_major_version_upgrade }}"
    skip_final_snapshot: "{{ skip_final_snapshot }}"
