---

#### Creating RDS subnet group ####

- name: Add or change a subnet group
  community.aws.rds_subnet_group:
    state: present
    name: "{{ subnet_group_name }}"
    description: "{{ subnet_group_description }}"
    region: "{{ region }}"
    subnets:
      - "{{ subnets_1 }}"
      - "{{ subnets_2 }}"

#### Creating RDS Parameter Group ####

- name: Creating Parameter Group
  community.aws.rds_param_group:
    state: present
    name: "{{ db_parameter_group_name }}"
    description: "{{ para_group_description }}"
    engine: "{{ para_engine }}"
    region: "{{ region }}"

#### Creating RDS Option Group ####

- name: Create an RDS sql option group
  community.aws.rds_option_group:
    state: present
    option_group_name: "{{ option_group_name }}"
    engine_name: "{{ engine_name }}"
    major_engine_version: "{{ major_engine_version }}"
    option_group_description: "{{  option_group_description }}"
    region: "{{ region }}"
    apply_immediately: true
  register: new_rds_mssql_option_group

#### Creating RDS instance ####

- name: create RDS instance
  community.aws.rds_instance:
    region: "{{ region }}"
    state: "present"
    engine: "{{ db_engine }}"
    license_model: "license-included"
    engine_version: "{{ db_engine_version }}"
    db_instance_identifier: "{{ instance_identifier}}"
    master_username: "{{ master_username }}"
    master_user_password: "{{ master_passwd }}"
    db_instance_class: "{{ instance_class }}"
    storage_type: "{{ storage_type }}"
    allocated_storage: "{{ allocated_storage }}"
    max_allocated_storage: "{{ max_allocated_storage }}"
    multi_az: "{{ multi_az }}"
    db_subnet_group_name: "{{ subnet_group_name }}"
    publicly_accessible: "{{ publicly_accessible }}"
    vpc_security_group_ids: "{{ vpc_security_group_id }}"
    port: "{{ port }}"
    backup_retention_period: "{{ backup_retention_period }}"
    storage_encrypted: "{{ storage_encrypted }}"
    kms_key_id: "{{ kms_key_id  }}"
    db_parameter_group_name: "{{ db_parameter_group_name }}"
    option_group_name: "{{ option_group_name }}"
    timezone: "{{ timezone }}"
    auto_minor_version_upgrade: "{{ auto_minor_version_upgrade }}"
    apply_immediately: "{{ apply_immediately }}"
    wait: "{{ wait }}"
    enable_iam_database_authentication: "{{ enable_iam_database_authentication }}"
    debug_botocore_endpoint_logs: "{{ debug_botocore_endpoint_logs }}"
    deletion_protection: "{{ deletion_protection }}"
    apply_immediately: "{{ apply_immediately }}"
    force_failover: "{{ force_failover }}"
    read_replica: "{{ read_replica }}"
    copy_tags_to_snapshot: "{{ copy_tags_to_snapshot }}"
    allow_major_version_upgrade: "{{ allow_major_version_upgrade }}"
    skip_final_snapshot: "{{ skip_final_snapshot }}"
